{% set name = "des-eastlake" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/des-science/eastlake/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2a6e17e912b4536c39735b5eb0ecf2b43f655b8e5c17f0ac5e5cf8c9bc797b99

build:
  # this recipe is not noarch due to using the scripts kwarg w/ setuptools
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    - fftw
    - libtool
    - autoconf
    - automake
    - cfitsio
    # only builds against openblas
    - openblas
  run:
    - libblas * *openblas
    - libcblas * *openblas
    - liblapack * *openblas
    - liblapacke * *openblas
    - openblas
    - libopenblas
    - python
    - astropy
    - cfitsio  # for fpack and builds
    - des-desmeds
    - des-pixcorrect
    - des-pizza-cutter-metadetect
    - esutil
    - fitsio
    - galsim
    - h5py
    - importlib_metadata
    - joblib
    - lsstdesc-coord
    - matplotlib-base
    - meds
    - metadetect
    - ngmix
    - numpy
    - numba
    - piff
    - pixmappy
    - psfex
    - pyyaml
    - scipy
    - setuptools
    - tqdm

test:
  imports:
    - eastlake
  commands:
    - eastlake-swarp -dd
    - eastlake-src-extractor -dd
    - run-eastlake-sim --help
    - python -c "import eastlake; assert eastlake.__version__ == '{{ version }}'"

about:
  home: https://github.com/des-science/eastlake
  license: BSD-3-Clause AND GPL-3.0-only
  license_file:
    - LICENSE
    - LICENSE-srcex
    - LICENSE-swarp
    - COPYRIGHT-srcex
    - COPYRIGHT-swarp
  summary: Y6 processing pipelines for balrog and image sims

extra:
  recipe-maintainers:
    - beckermr
